name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker image build
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/unitor-gym-api:0.2.7
      - name: Push to Docker Hub
        run: docker push ${{secrets.DOCKER_USER}}/unitor-gym-api:0.2.7
